import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import Navbar from './Navbar'
import { Suspense } from 'react'
import { SessionProvider } from 'next-auth/react'
import AuthProvider from './auth/Provider'
const inter = Inter({ subsets: ['latin'] })
// import localFont from from 'next/font/local',  
const roboto= Roboto({
  subsets:['latin'],
  weight:['400','500']
})

//add localfont the same way
// const fontName= localFont({
//   src:'../public/fonts/fontname.woff2 (extension name)'
//   variable: '--font--fontName'
// })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  //for meata tags
  openGraph:{
    title:'...',
    description:'...'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html data-theme="cmyk" lang="en">
      <body className={roboto.className}> 
      <AuthProvider>
          <Navbar/> 
          <main className='p-5'>
              {children}   
          </main> 
      </AuthProvider>
      </body>
    </html>
  )
}
